version: '3.5'
services:
  app:
    container_name: tinyme-app
    image: dersonsena/php-8.0
    command: php -S 0.0.0.0:80 -t /usr/src/app/public
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - '8081:80'